import { RiInstagramLine } from "react-icons/ri";
import { RiTiktokFill } from "react-icons/ri";
import { RiTwitterXFill } from "react-icons/ri";

export const socialMedias = [
    {
        id: 1, icon: RiInstagramLine, link: 'https://www.instagram.com/tomso.app/', label: 'Visit my Instagram profile.',
    },
    {
        id: 2, icon: RiTiktokFill, link: 'https://www.tiktok.com/@tomso.js?lang=es', label: 'Visit my TikTok profile.',
    },
    {
        id: 3, icon: RiTwitterXFill, link: 'https://x.com/TomsoJS', label: 'Visit my Twitter profile.',
    },
]

export const coins = [
    { id: 1, code: "ADA", name: "Cardano" },
    { id: 2, code: "AED", name: "Dírham de los Emiratos Árabes Unidos" },
    { id: 3, code: "AFN", name: "Afgani Afgano" },
    { id: 4, code: "ALL", name: "Lek albanés" },
    { id: 5, code: "AMD", name: "Dram armenio" },
    { id: 6, code: "ANG", name: "Guilder de las Antillas Neerlandesas" },
    { id: 7, code: "AOA", name: "Kwanza angoleño" },
    { id: 8, code: "ARS", name: "Peso argentino" },
    { id: 9, code: "AUD", name: "Dólar australiano" },
    { id: 10, code: "AZN", name: "Manat azerbaiyano" },
    { id: 11, code: "BAM", name: "Marco convertible de Bosnia y Herzegovina" },
    { id: 12, code: "BBD", name: "Dólar barbadeño" },
    { id: 13, code: "BDT", name: "Taka bangladesí" },
    { id: 14, code: "BGN", name: "Lev búlgaro" },
    { id: 15, code: "BHD", name: "Dinar bareiní" },
    { id: 16, code: "BIF", name: "Franco burundés" },
    { id: 17, code: "BMD", name: "Dólar bermudeño" },
    { id: 18, code: "BNB", name: "Binance Coin" },
    { id: 19, code: "BND", name: "Dólar de Brunéi" },
    { id: 20, code: "BOB", name: "Boliviano" },
    { id: 21, code: "BRL", name: "Real brasileño" },
    { id: 22, code: "BSD", name: "Dólar bahameño" },
    { id: 23, code: "BTC", name: "Bitcoin" },
    { id: 24, code: "BTN", name: "Ngultrum butanés" },
    { id: 25, code: "BWP", name: "Pula de Botsuana" },
    { id: 26, code: "BYN", name: "Rublo bielorruso" },
    { id: 27, code: "BYR", name: "Rublo bielorruso (antiguo)" },
    { id: 28, code: "BZD", name: "Dólar beliceño" },
    { id: 29, code: "CAD", name: "Dólar canadiense" },
    { id: 30, code: "CDF", name: "Franco congoleño" },
    { id: 31, code: "CHF", name: "Franco suizo" },
    { id: 32, code: "CLF", name: "Unidad de Fomento chilena" },
    { id: 33, code: "CLP", name: "Peso chileno" },
    { id: 34, code: "CNY", name: "Yuan chino" },
    { id: 35, code: "COP", name: "Peso colombiano" },
    { id: 36, code: "CRC", name: "Colón costarricense" },
    { id: 37, code: "CUC", name: "Peso cubano convertible" },
    { id: 38, code: "CUP", name: "Peso cubano" },
    { id: 39, code: "CVE", name: "Escudo caboverdiano" },
    { id: 40, code: "CZK", name: "Corona checa" },
    { id: 41, code: "DAI", name: "Dai" },
    { id: 42, code: "DJF", name: "Franco yibutiano" },
    { id: 43, code: "DKK", name: "Corona danesa" },
    { id: 44, code: "DOP", name: "Peso dominicano" },
    { id: 45, code: "DOT", name: "Polkadot" },
    { id: 46, code: "DZD", name: "Dinar argelino" },
    { id: 47, code: "EGP", name: "Libra egipcia" },
    { id: 48, code: "ERN", name: "Nakfa eritreo" },
    { id: 49, code: "ETB", name: "Birr etíope" },
    { id: 50, code: "ETH", name: "Ethereum" },
    { id: 51, code: "EUR", name: "Euro" },
    { id: 52, code: "FJD", name: "Dólar fijiano" },
    { id: 53, code: "FKP", name: "Libra de las Islas Malvinas" },
    { id: 54, code: "GBP", name: "Libra esterlina" },
    { id: 55, code: "GEL", name: "Lari georgiano" },
    { id: 56, code: "GGP", name: "Libra de Guernsey" },
    { id: 57, code: "GHS", name: "Cedi ghanés" },
    { id: 58, code: "GIP", name: "Libra de Gibraltar" },
    { id: 59, code: "GMD", name: "Dalasi gambiano" },
    { id: 60, code: "GNF", name: "Franco guineano" },
    { id: 61, code: "GTQ", name: "Quetzal guatemalteco" },
    { id: 62, code: "GYD", name: "Dólar guyanés" },
    { id: 63, code: "HKD", name: "Dólar de Hong Kong" },
    { id: 64, code: "HNL", name: "Lempira hondureña" },
    { id: 65, code: "HRK", name: "Kuna croata" },
    { id: 66, code: "HTG", name: "Gourde haitiano" },
    { id: 67, code: "HUF", name: "Forinto húngaro" },
    { id: 68, code: "IDR", name: "Rupia indonesia" },
    { id: 69, code: "ILS", name: "Shekel israelí" },
    { id: 70, code: "IMP", name: "Libra de la Isla de Man" },
    { id: 71, code: "INR", name: "Rupia india" },
    { id: 72, code: "IQD", name: "Dinar iraquí" },
    { id: 73, code: "IRR", name: "Riyal iraní" },
    { id: 74, code: "ISK", name: "Corona islandesa" },
    { id: 75, code: "JEP", name: "Libra de Jersey" },
    { id: 76, code: "JMD", name: "Dólar jamaiquino" },
    { id: 77, code: "JOD", name: "Dinar jordano" },
    { id: 78, code: "JPY", name: "Yen japonés" },
    { id: 79, code: "KES", name: "Chelín keniano" },
    { id: 80, code: "KGS", name: "Som kirguís" },
    { id: 81, code: "KHR", name: "Rupia camboyana" },
    { id: 82, code: "KMF", name: "Franco comorense" },
    { id: 83, code: "KPW", name: "Won de Corea del Norte" },
    { id: 84, code: "KRW", name: "Won de Corea del Sur" },
    { id: 85, code: "KWD", name: "Dinar kuwaití" },
    { id: 86, code: "KYD", name: "Dólar de las Islas Caimán" },
    { id: 87, code: "KZT", name: "Tenge kazajo" },
    { id: 88, code: "LAK", name: "Kip laosiano" },
    { id: 89, code: "LBP", name: "Libra libanesa" },
    { id: 90, code: "LKR", name: "Rupia de Sri Lanka" },
    { id: 91, code: "LRD", name: "Dólar liberiano" },
    { id: 92, code: "LSL", name: "Loti lesotense" },
    { id: 93, code: "LTC", name: "Litecoin" },
    { id: 94, code: "LTL", name: "Litas lituano" },
    { id: 95, code: "LVL", name: "Lat de Letonia" },
    { id: 96, code: "LYD", name: "Dinar libio" },
    { id: 97, code: "MAD", name: "Dirham marroquí" },
    { id: 98, code: "MATIC", name: "Polygon" },
    { id: 99, code: "MDL", name: "Leu moldavo" },
    { id: 100, code: "MGA", name: "Ariary malgache" },
    { id: 101, code: "MKD", name: "Dinar macedonio" },
    { id: 102, code: "MMK", name: "Kyat birmano" },
    { id: 103, code: "MNT", name: "Tugrik mongol" },
    { id: 104, code: "MOP", name: "Pataca de Macao" },
    { id: 105, code: "MRO", name: "Ouguiya mauritana" },
    { id: 106, code: "MRU", name: "Ouguiya mauritana (nuevo)" },
    { id: 107, code: "MUR", name: "Rupia mauriciana" },
    { id: 108, code: "MVR", name: "Rufiyaa maldiva" },
    { id: 109, code: "MWK", name: "Kwacha malauí" },
    { id: 110, code: "MXN", name: "Peso mexicano" },
    { id: 111, code: "MYR", name: "Ringgit malayo" },
    { id: 112, code: "MZN", name: "Metical mozambiqueño" },
    { id: 113, code: "NAD", name: "Dólar namibio" },
    { id: 114, code: "NGN", name: "Naira nigeriana" },
    { id: 115, code: "NIO", name: "Córdoba nicaragüense" },
    { id: 116, code: "NOK", name: "Corona noruega" },
    { id: 117, code: "NPR", name: "Rupia nepalí" },
    { id: 118, code: "NZD", name: "Dólar neozelandés" },
    { id: 119, code: "OMR", name: "Riyal omaní" },
    { id: 120, code: "OP", name: "Optimism" },
    { id: 121, code: "PAB", name: "Balboa panameño" },
    { id: 122, code: "PEN", name: "Sol peruano" },
    { id: 123, code: "PGK", name: "Kina de Papúa Nueva Guinea" },
    { id: 124, code: "PHP", name: "Peso filipino" },
    { id: 125, code: "PKR", name: "Rupia pakistaní" },
    { id: 126, code: "PLN", name: "Zloty polaco" },
    { id: 127, code: "PYG", name: "Guaraní paraguayo" },
    { id: 128, code: "QAR", name: "Riyal catarí" },
    { id: 129, code: "RON", name: "Leu rumano" },
    { id: 130, code: "RSD", name: "Dinar serbio" },
    { id: 131, code: "RUB", name: "Rublo ruso" },
    { id: 132, code: "RWF", name: "Franco ruandés" },
    { id: 133, code: "SAR", name: "Riyal saudí" },
    { id: 134, code: "SBD", name: "Dólar de las Islas Salomón" },
    { id: 135, code: "SCR", name: "Rupia seychelense" },
    { id: 136, code: "SDG", name: "Libra sudanesa" },
    { id: 137, code: "SEK", name: "Corona sueca" },
    { id: 138, code: "SGD", name: "Dólar de Singapur" },
    { id: 139, code: "SHP", name: "Libra de Santa Elena" },
    { id: 140, code: "SLE", name: "León de Sierra Leona" },
    { id: 141, code: "SLL", name: "León de Sierra Leona (nuevo)" },
    { id: 142, code: "SOL", name: "Solana" },
    { id: 143, code: "SOS", name: "Chelín somalí" },
    { id: 144, code: "SRD", name: "Dólar surinamés" },
    { id: 145, code: "STD", name: "Dólar de São Tomé y Príncipe" },
    { id: 146, code: "STN", name: "Dólar de São Tomé y Príncipe (nuevo)" },
    { id: 147, code: "SVC", name: "Colón salvadoreño" },
    { id: 148, code: "SYP", name: "Libra siria" },
    { id: 149, code: "SZL", name: "Lilangeni suazi" },
    { id: 150, code: "THB", name: "Baht tailandés" },
    { id: 151, code: "TJS", name: "Somoni tayiko" },
    { id: 152, code: "TMT", name: "Manat turkmeno" },
    { id: 153, code: "TND", name: "Dinar tunecino" },
    { id: 154, code: "TOP", name: "Paʻanga tongano" },
    { id: 155, code: "TRY", name: "Lira turca" },
    { id: 156, code: "TTD", name: "Dólar de Trinidad y Tobago" },
    { id: 157, code: "TWD", name: "Dólar taiwanés" },
    { id: 158, code: "TZS", name: "Chelín tanzano" },
    { id: 159, code: "UAH", name: "Grivna ucraniana" },
    { id: 160, code: "UGX", name: "Chelín ugandés" },
    { id: 161, code: "USD", name: "Dólar estadounidense" },
    { id: 162, code: "USDC", name: "USD Coin" },
    { id: 163, code: "USDT", name: "Tether" },
    { id: 164, code: "UYU", name: "Peso uruguayo" },
    { id: 165, code: "UZS", name: "Som uzbeko" },
    { id: 166, code: "VEF", name: "Bolívar fuerte venezolano" },
    { id: 167, code: "VES", name: "Bolívar soberano" },
    { id: 168, code: "VND", name: "Dong vietnamita" },
    { id: 169, code: "VUV", name: "Vatu vanuatuense" },
    { id: 170, code: "WST", name: "Tala samoano" },
    { id: 171, code: "XAF", name: "Franco CFA" },
    { id: 172, code: "XAG", name: "Plata" },
    { id: 173, code: "XAU", name: "Oro" },
    { id: 174, code: "XCD", name: "Dólar del Caribe Oriental" },
    { id: 175, code: "XDR", name: "Derechos especiales de giro" },
    { id: 176, code: "XOF", name: "Franco CFA" },
    { id: 177, code: "XPD", name: "Paladio" },
    { id: 178, code: "XPF", name: "Franco" },
    { id: 179, code: "XPT", name: "Onza de platino" },
    { id: 180, code: "XRP", name: "Criptomoneda" },
    { id: 181, code: "YER", name: "Rial yemení" },
    { id: 182, code: "ZAR", name: "Rand sudafricano" },
    { id: 183, code: "ZMK", name: "Kwacha zambiano" },
    { id: 184, code: "ZMW", name: "Kwacha zambiano" },
    { id: 185, code: "ZWG", name: "Oro de Zimbabue" },
    { id: 186, code: "ZWL", name: "Dólar zimbabuense" },
]
